# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"assert_eq": "00_core.ipynb",
         "pivot_vs": "00_core.ipynb",
         "display": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ddobrinskiy.github.io/ml_utils/"

git_url = "https://github.com/ddobrinskiy/ml_utils/tree/master/"

def custom_doc_links(name): return None
